### ISSUE TITLE
transtion问题

### ISSUE THREAD

**Issue by byning2012** [OCNYang/Android-Animation-Set#2]
transition

- [   startActivity(slideByCodeIntent, ActivityOptionsCompat.makeSceneTransitionAnimation(this, (android.support.v4.util.Pair<View, String>) null).toBundle()); ]

这个参数shareElements是不是必传参数了?不传好像都编译不过去

**Comment by OCNYang** [comment]
```
public static ActivityOptionsCompat makeSceneTransitionAnimation(@NonNull Activity activity,
            @NonNull View sharedElement, @NonNull String sharedElementName)
```

```
public static ActivityOptionsCompat makeSceneTransitionAnimation(@NonNull Activity activity,
            Pair<View, String>... sharedElements)
```

注意方法中的`@NonNull` 注解。使用第二个方法，第二个参数是可以为空的。

**Comment by byning2012** [comment]
一开始我也是这么写的，也不可以这是我的代码和报错
`   val slideByCodeIntent = Intent(this@ShopCategoryListActivity, ShopDetailsActivity::class.java)
        slideByCodeIntent.putExtra("name", "name")

 startActivity(slideByCodeIntent, ActivityOptionsCompat.makeSceneTransitionAnimation(this@ShopCategoryListActivity, null).toBundle())`
报错信息
`  java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.support.v4.util.Pair.first' on a null object reference`

**Comment by byning2012** [comment]
@OCNYang

**Comment by byning2012** [comment]
debug追踪了一下，我知道原因了，在kotlin里面传null，在这个方法里面它处理成pair[1]了也就是有值，所以在kotlin里面用转场动画的时候不需要传任何值，下面是代码
` startActivity(slideByCodeIntent, ActivityOptionsCompat.makeSceneTransitionAnimation(this@ShopCategoryListActivity).toBundle())`
当你传null的时候
![Uploading image.png…]()

**Comment by OCNYang** [comment]
要慢慢体验 Kotlin 的各种踩坑 :laughing:

**Comment by byning2012** [comment]
@OCNYang **我关了，原因也知道了，就是它是参数可变数组，传null的时候kotlin处理成第一个数组了，慢慢踩吧__**
