### ISSUE TITLE
大神有没有用过Lottie动画？效果怎样？

### ISSUE THREAD

**Issue by yy476853155** [OCNYang/Android-Animation-Set#4]
新项目中打算用这个库，但是不知道内存、兼容性等方面会不会有什么问题。如果大神了解这个库麻烦解答一下。

**Comment by OCNYang** [comment]
在某些方面（例如加载动图等） Lottie 比原生动画有着更大的优势，动画效果也会更细腻。你可以放心使用，不会给你的内存带来压力；也不会有兼容性的问题的。唯一给你的带来的额外工作，是你要确保你家美工有这方面的功底。
