### ISSUE TITLE
请问这个编译打包错误如何解决

### ISSUE THREAD

**Issue by shitouzhang** [OCNYang/Android-Animation-Set#5]
Failed to find byte code for android/graphics/drawable/Animatable2$AnimationCallback，我看官方这个回调是在added in API level 23中可以使用，为什么我总是编译可以，就是打包apk的时候报这个错误，谢谢

**Comment by OCNYang** [comment]
我这边编译、打包都没有问题，我从GitHub上下载zip包重新在本地编译，也是没有问题。所以我很难知道你们为什么会遇到这些问题，我想是不是你们 AS 的本地环境配置不同造成的，请尝试保持项目原有的Gradle版本，版本信息可以参照：

https://github.com/OCNYang/Android-Animation-Set/blob/766d64409de10b9121fd1c0616147c43a18e015c/build.gradle#L10

https://github.com/OCNYang/Android-Animation-Set/blob/766d64409de10b9121fd1c0616147c43a18e015c/gradle/wrapper/gradle-wrapper.properties#L6

**Comment by shitouzhang** [comment]
多谢回复，我按照你的版本试下，原来我编译和打包都是用的最新版的gradle
