### ISSUE TITLE
Vector 第三个模块点击无效果

### ISSUE THREAD

**Issue by grs007** [OCNYang/Android-Animation-Set#7]
没有动画效果，为什么？

**Comment by OCNYang** [comment]
是说奔跑的图钉？点击后无效果吗？
![](https://raw.githubusercontent.com/OCNYang/Android-Animation-Set/master/README_Res/vector_anim.gif?token=AQ83MkaFkHlYPvrYr6vNPoJBfJAJjuspks5axebVwA%3D%3D)
